/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio;

import javax.swing.JComboBox;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.JTree;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Usuario
 */
public class MainFrame extends javax.swing.JFrame {

    NaryTree tree = new NaryTree();
    DefaultTreeModel treeModel;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        DefaultMutableTreeNode n = new DefaultMutableTreeNode("EDT");
        treeModel = new DefaultTreeModel(n);
        graphicalTree.setModel(treeModel);
        DefaultMutableTreeNode Fake = new DefaultMutableTreeNode("");
        treeModel.insertNodeInto(Fake, n, n.getChildCount());
        tree.setTitle("EDT");
        jComboBox1.addItem(n);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JTabbedPane();
        edtPane = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        nodeField = new javax.swing.JTextField();
        packageButton = new javax.swing.JButton();
        deliverableButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        graphicalTree = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Error = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyect Management Office");

        jComboBox1.setToolTipText("Seleccione aqui donde desea insertar");

        packageButton.setText("Insertar paquete");
        packageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageButtonActionPerformed(evt);
            }
        });

        deliverableButton.setText("Insertar entregable");
        deliverableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverableButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(graphicalTree);

        jLabel1.setText("Insertar en:");

        jLabel2.setText("Nombre de paquete/entregable:");

        Error.setBackground(new java.awt.Color(255, 51, 51));
        Error.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Error.setForeground(new java.awt.Color(255, 0, 0));
        Error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("Nota: Al crear un paquete se le asigna de hijo un entregable temporal sin nombre");

        javax.swing.GroupLayout edtPaneLayout = new javax.swing.GroupLayout(edtPane);
        edtPane.setLayout(edtPaneLayout);
        edtPaneLayout.setHorizontalGroup(
            edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edtPaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edtPaneLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(edtPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(edtPaneLayout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(edtPaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                                .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(edtPaneLayout.createSequentialGroup()
                                        .addComponent(packageButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(deliverableButton))
                                    .addComponent(nodeField)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(30, 30, 30))))
        );
        edtPaneLayout.setVerticalGroup(
            edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edtPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(edtPaneLayout.createSequentialGroup()
                        .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(packageButton)
                            .addComponent(deliverableButton))
                        .addGap(35, 35, 35)
                        .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        mainPane.addTab("EDT", edtPane);

        getContentPane().add(mainPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void packageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageButtonActionPerformed
        if (!check(nodeField.getText())) return;
        DefaultMutableTreeNode n = new DefaultMutableTreeNode(nodeField.getText());
        DefaultMutableTreeNode Fake = new DefaultMutableTreeNode("");
        DefaultMutableTreeNode parent = (DefaultMutableTreeNode) jComboBox1.getSelectedItem();
        if(parent.getChildAt(0).toString() == ""){
            treeModel.removeNodeFromParent((MutableTreeNode)parent.getChildAt(0));
        }  
        treeModel.insertNodeInto(n, parent, parent.getChildCount());
        treeModel.insertNodeInto(Fake, n, n.getChildCount());
        tree.insertPackageNode(parent.toString(), n.toString());
        jComboBox1.addItem(n);
    }//GEN-LAST:event_packageButtonActionPerformed

    private void deliverableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverableButtonActionPerformed
        if (!check(nodeField.getText())) return;
        DefaultMutableTreeNode n = new DefaultMutableTreeNode(nodeField.getText());
        DefaultMutableTreeNode parent = (DefaultMutableTreeNode) jComboBox1.getSelectedItem();
        if(parent.getChildAt(0).toString() == ""){
            treeModel.removeNodeFromParent((MutableTreeNode)parent.getChildAt(0));
        }    
        treeModel.insertNodeInto(n, parent, parent.getChildCount());
        tree.insertDerivableNode(parent.toString(), n.toString(), "This is the content of the file");
    }//GEN-LAST:event_deliverableButtonActionPerformed

    public boolean check(String nombre){
        if (nombre.equals("")){
            Error.setText("No se pueden insertar paquetes/entregables sin nombre");
            return false;
        } else{
            Error.setText("");
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Error;
    private javax.swing.JButton deliverableButton;
    private javax.swing.JPanel edtPane;
    private javax.swing.JTree graphicalTree;
    private javax.swing.JComboBox<DefaultMutableTreeNode> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JTextField nodeField;
    private javax.swing.JButton packageButton;
    // End of variables declaration//GEN-END:variables
}
