/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio;

import javax.swing.JComboBox;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.JTree;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Usuario
 */
public class MainFrame extends javax.swing.JFrame {

    NaryTree tree = new NaryTree();
    DefaultTreeModel treeModel;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        DefaultMutableTreeNode n = new DefaultMutableTreeNode("EDT");
        treeModel = new DefaultTreeModel(n);
        graphicalTree.setModel(treeModel);
        jComboBox1.addItem(n);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JTabbedPane();
        edtPane = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        nodeField = new javax.swing.JTextField();
        packageButton = new javax.swing.JButton();
        deliverableButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        graphicalTree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyect Managment Office");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jComboBox1.setToolTipText("Seleccione aqui donde desea insertar");

        packageButton.setText("Insertar paquete");
        packageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageButtonActionPerformed(evt);
            }
        });

        deliverableButton.setText("Insertar entregable");

        graphicalTree.setShowsRootHandles(true);
        jScrollPane1.setViewportView(graphicalTree);

        javax.swing.GroupLayout edtPaneLayout = new javax.swing.GroupLayout(edtPane);
        edtPane.setLayout(edtPaneLayout);
        edtPaneLayout.setHorizontalGroup(
            edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edtPaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(edtPaneLayout.createSequentialGroup()
                        .addComponent(packageButton)
                        .addGap(18, 18, 18)
                        .addComponent(deliverableButton))
                    .addComponent(nodeField)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        edtPaneLayout.setVerticalGroup(
            edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edtPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(edtPaneLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(edtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(packageButton)
                            .addComponent(deliverableButton))))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        mainPane.addTab("EDT", edtPane);

        getContentPane().add(mainPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void packageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageButtonActionPerformed
        DefaultMutableTreeNode n = new DefaultMutableTreeNode(nodeField.getText());
        DefaultMutableTreeNode parent = (DefaultMutableTreeNode) jComboBox1.getSelectedItem();
        treeModel.insertNodeInto(n, parent, parent.getChildCount());
        jComboBox1.addItem(n);
    }//GEN-LAST:event_packageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deliverableButton;
    private javax.swing.JPanel edtPane;
    private javax.swing.JTree graphicalTree;
    private javax.swing.JComboBox<DefaultMutableTreeNode> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JTextField nodeField;
    private javax.swing.JButton packageButton;
    // End of variables declaration//GEN-END:variables
}
